services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

### Nie działa :(
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - VITE_API_BASE_URL=http://backend:8080/api
  #     - VITE_DEFAULT_LAT=52.237049
  #     - VITE_DEFAULT_LNG=21.017532
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

networks:
  app-network: